### PR TITLE
Add NH Governor

### LINKED ISSUE #94: Create form for NH Governor: 5
https://new-hampshire.secure.force.com/support/GOV_Opinion

### PR DESCRIPTION
**Pull request by jason44406**
Fixes #94

### CODE REVIEW

**Comment by jason44406** [comment]
@jasonkb @chris-erickson @csnardi 
Guys, Do we store the constituent city in a consistent format?  This form has a select for the city, with the names capitalized properly.  In my experience, users can enter text in ways that may not conform.  Will this be an issue for this form?

**Comment by chris-erickson** [comment]
It’s USPS validated, I believe, but is probably all caps when you pick it off a message.

**Comment by csnardi** [comment]
Yeah, I believe Smarty Streets always returns an all-caps version of everything (street name, city, state).

**Comment by jason44406** [comment]
OK.  My tests worked, so I think we can pick the city from the select without issue.

**Pull request merged**
