### PR TITLE
Update Maryland governor form config

### PR DESCRIPTION
**Pull request by csnardi**
When the Maryland governor's form switched to a new URL, the page itself also changed. Update the form config for the new page.

### CODE REVIEW

**Comment by csnardi** [comment]
That's what I've been doing, just out of the principle of sharing less data when it's not needed.

**Comment by csnardi** [comment]
I think it makes more sense to leave out non-required information when it's like phone numbers/etc since I believe under some state laws their message is a public record, which may not be the intent of whoever is sending the message.

**Comment by csnardi** [comment]
I think that information required to verify someone is a constituent (e.g. address) and general information (names, emails) are probably best to always use, and phone numbers are probably the only one I wouldn't add if not required.

**Comment by jasonkb** [comment]
Sounds good to me -- to include if possible everything except phone number. Maybe add that to the contact-officials/README.md?

**Pull request merged**
