### PR TITLE
IL Governor

### PR DESCRIPTION
**Pull request by brianm**
Work in Progress for #56 -- DO NOT MERGE

### CODE REVIEW

**Comment by jasonkb** [comment]
Looks good! Just `US_STATES` needs to be filled in?

**Comment by jasonkb** [comment]
@brianm Hi! This is all good except for changing `US_STATES` to list of states eh? Let me know how I can help!

**Comment by csnardi** [comment]
The `US_STATES` is actually probably fine, it's what I've been doing since it's defined at https://github.com/unitedstates/contact-congress/blob/master/support/constants.yaml#L4. However, I don't think this form config has been fully updated yet for the IL form.

**Comment by jasonkb** [comment]
@csnardi @brianm WHOA!!!! We should update all our configs to use that!

**Comment by brianm** [comment]
It has NOT been fully updated yet. I came down with flu and hid on sofa for a week :-(

**Comment by jasonkb** [comment]
Oh no, feel better!!!!

**Comment by jasonkb** [comment]
@brianm @csnardi @jason44406 @chris-erickson I finished this guy off if you want to take a look!

**Pull request merged**
